sudo: required

services:
    - docker

language: python

branches:
    only:
        - master

python:
    - '2.7'

before_install:
    - git fetch --unshallow

install:
    - pip install -U pybuilder
    - pyb -X install_dependencies

script:
    - pyb -X all
    - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then
        docker tag c-bastion:latest immobilienscout24/c-bastion:latest ;
        docker tag c-bastion:latest immobilienscout24/c-bastion:$( git rev-list --count HEAD ) ;
        docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" ;
        docker push immobilienscout24/c-bastion ;
      else
        echo "skipping Docker upload" ;
      fi
