sudo: required

services:
    - docker

language: python

branches:
    only:
        - master

python:
    - '2.7'

before_install:
    - git fetch --unshallow
    - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-de

install:
    - pip install -U pybuilder
    - pyb -X install_dependencies

script:
    - make

after_success:
  - docker tag cbastion:latest immobilienscout24/cbastion:latest
  - docker tag cbastion:latest immobilienscout24/cbastion:$( git rev-list --count HEAD )
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push immobilienscout24/cbastion
