sudo: required

services:
    - docker

language: python

branches:
    only:
        - master

python:
    - '2.7'

before_install:
    - git fetch --unshallow

install:
    - pip install -U pybuilder
    - pyb -v install_dependencies

script:
    - make

after_success:
  - docker tag cbastion:latest immobilienscout24/cbastion:latest
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push immobilienscout24/cbastion
