sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t cbastion:latest .
  - docker tag cbastion:latest programmieramt/cbastion:latest
  - docker push programmieramt/cbastion

